add new crmUrl validator
retailcrm/mg-transport-core pull request #27
Opened 2021-07-14 13:44 UTC by Chazovs

2021-07-19 09:48 UTC, Neur0toxine requested changes
Логика проверки достаточно сложна. Сначала проверяются те части URL, которые не нужны / имеют фиксированные значения. Затем генерируется список доменов 3-го уровня из списка допустимых хостов. Затем проверяется всё по этому списку.

Сложно. А как можно проще?

Сначала нужно проверить фиксированные части URL (дополнительно к уже проверяемым). Затем из хостнейма предоставленного URL нужно убрать первую часть с точкой. Например, для хоста `test.retailcrm.pro` это будет `retailcrm.pro`. После этого полученный результат можно будет просто сравнить со списком доменов, который просто был скачан по ссылке. Это быстрее и проще, чем генерировать домены вида `test.retailcrm.ru`, `test.retailcrm.pro` для каждого допустимого хоста.

Также рекомендую присмотреться к стилю кода в других файлах. Строгого стиля в Go нет - достаточно того, что линтер не ругается. Здесь код рабочий и неплохой - просто написан в стиле PSR, что делает его несколько разреженным.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +}
А зачем нужен этот метод? Он же буквально ничего не делает полезного. Вызывающий код в `isDomainValid` можно заменить таким:

```go
parseUrl, err := url.ParseRequestURI(crmUrl)
if err != nil {
	return false
}
```

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +		}
Более краткая запись выглядит так:
```go
if err := body.Close(); err != nil {
	panic(err)
}
```

Как мне кажется, панику здесь излишне бросать.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	defer func(Body io.ReadCloser) {
Как правило параметры функции в `camelCase` указываются.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +func getDomainsByStore(store string, client *http.Client) []Domain {
Было бы логично если бы HTTP-клиент создавался бы с модификацией его параметров. Но это обычный HTTP-клиент с бесконечным таймаутом.

Здесь лучше использовать `http.DefaultClient`. Особенно в контексте транспортов т.к. в них он подменяется в рантайме на клиент с фиксированным таймаутом.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	req, _ := http.NewRequest("GET", store, nil)
Здесь не обрабатывается ошибка. Также пакет `net/http` предоставляет константы методов, например, `http.MethodGet`. Полный список можно увидеть [здесь](https://pkg.go.dev/net/http#pkg-constants).

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	respBody, _ := ioutil.ReadAll(resp.Body)
Здесь не обрабатываются ошибки. В либе версия Go указана как 1.13 - поэтому `ioutil` допустимо. На заметку всё же стоит взять что `ioutil` с Go 1.16 устарел - используется просто `io`.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	if err != nil {
Допустима краткая запись.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	var parseUrl = getParseUrl(crmUrl)
Тут краткая запись присваивания рекомендуется.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	var crmDomains = getValidDomains(parseUrl.Hostname())
Аналогично предыдущему.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	}
Слишком мало частей URL проверяются. Валидатор должен допускать следующее:
* схема `https:`;
* хостнейм - домен третьего уровня, второй уровень домена - один из списка разрешённых;
* если есть path, то это только `/`.
* всех остальных частей URL (query, fragment и т.д.) не должно быть.

2021-07-19 09:48 UTC, Neur0toxine commented on core/validator.go
> +	crmDomains := getDomainsByStore("https://infra-data.retailcrm.tech/crm-domains.json", &http.Client{})
Возможно, стоит вынести ссылки в константы, в верхнюю часть файла.

2021-07-19 12:45 UTC, Chazovs commented on core/validator.go
> +	}
уровень домена проверять нет смысла, так как по сути мы проверим это, когда буде сверять с валидными доменами. схему и путь я и так проверяю. проверку query и fragment добавил.

2021-07-19 14:25 UTC, Neur0toxine commented on core/validator.go
> +	}
Да, я просто целиком схему описал здесь.

2021-07-19 14:41 UTC, Neur0toxine requested changes

2021-07-19 14:41 UTC, Neur0toxine commented on core/validator.go
> +	return result
Лишняя переменная здесь.

2021-07-19 14:41 UTC, Neur0toxine commented on core/validator.go
> +	}
А если появится `retailcrm.co.uk`?

2021-07-19 14:41 UTC, Neur0toxine commented on core/validator.go
> +}
`domainDeep` на самом деле не нужна (см. выше почему). Логика всей функции сводится к одной строчке:
```go
return strings.Join(strings.Split(hostname, ".")[1:], ".")
```

2021-07-19 14:41 UTC, Neur0toxine commented on core/validator.go
> +	}
Не нужно сравнивать булевое возвращаемое значение с true. Достаточно `if checkDomains(...)`.
Также по коду нужно пройтись через `gofmt` перед коммитом.

2021-07-19 14:41 UTC, Neur0toxine commented on core/validator.go
> +	crmDomains := getDomainsByStore(domainsStoreUrl, http.DefaultClient)
Не нужно передавать `http.DefaultClient` туда. Пусть он внутри метода используется напрямую.

2021-07-19 14:41 UTC, Neur0toxine commented on core/validator.go
> +}
Неполная проверка. В частности, должны отсекаться basic auth доступы - тут этого нет.
https://pkg.go.dev/net/url#URL

2021-07-21 09:49 UTC, Neur0toxine requested changes

2021-07-21 09:49 UTC, Neur0toxine commented on core/validator.go
> +	}
`parseUrl.User` может быть `nil` - это нужно учесть.

2021-07-26 10:30 UTC, Neur0toxine requested changes

2021-07-26 10:30 UTC, Neur0toxine commented on core/validator.go
> +	}
Проверять, что `parseURL` не `nil` нужно до обращения к нему. В противном случае эта проверка бесполезна.

2021-07-26 10:30 UTC, Neur0toxine commented on core/validator.go
> +	}
Достаточно проверять, что просто `.User` есть. Если это так - уже надо возвращать ошибку.

2021-07-27 11:29 UTC, merged